# Generated by Django 4.0.3 on 2022-03-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='digital',
        ),
        migrations.AddField(
            model_name='meal',
            name='describtion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
