# Generated by Django 4.0.3 on 2022-03-16 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_remove_meal_digital_meal_describtion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='describtion',
            new_name='description',
        ),
    ]
